quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017/quarkus
    database: quarkus
    hosts:
      - host: localhost
        port: 27017

  # datasource:
  #   db-kind: postgresql
  #   username: postgres
  #   password: "@Potter77"
  #   jdbc:
  #     driver: org.postgresql.Driver
  #     url: jdbc:postgresql://localhost:5432/postgres

  # hibernate-orm:
  #   database:
  #     generation:
  #       create-source: metadata-then-script
  #       scripts:
  #         create-target: create.sql
  #         drop-target: drop.sql
  #   log:
  #     sql: true
  #     format_sql: true
  #   dialect:
  #     database: postgresql
  #     show-sql: true
